<a href="https://colab.research.google.com/github/ullattil/Self-Study-Notebooks/blob/master/iml_pytorch_tutorial1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# IML PyTorch Tutorial - Part 1: Tensors and Arithmetic Operations


PyTorch **tensors**:
*   Data structure that is very similar to arrays / matrices in NumPy (i.e. `np.ndarrays`)
*   Can be stored on GPUs and other accelerated computing hardware
*   Also have (hidden) attributes and methods that make automatic differentiation possible






In [ ]:
# basic imports
import torch
import numpy as np

### Defining a tensor


There are different ways to define a tensor in PyTorch

With custum data definition:

In [ ]:
# define a matix
data = [[1, 2.5], [3.5, 4]]
x_tensor = torch.tensor(data)

# check some properties of the tensor
print(x_tensor, '\n')
print('Shape:', x_tensor.shape)
print('Data type:', x_tensor.dtype)
print('Device:', x_tensor.device)

tensor([[1.0000, 2.5000],
        [3.5000, 4.0000]]) 

Shape: torch.Size([2, 2])
Data type: torch.float32
Device: cpu


With constant or random values:

In [ ]:
shape = (2, 3, 5)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
rand_tensor = torch.rand(shape)  # samples from a U([0, 1]) uniform dist
randn_tensor = torch.randn(shape)  # samples from a N(0, 1) standard normal dist


print(f"Ones tensor: \n{ones_tensor} \n")
print(f"Zeros tensor: \n{zeros_tensor} \n")
print(f"Random (uniform) tensor: \n{rand_tensor} \n")
print(f"Random (Gaussian) tensor: \n{randn_tensor}")

Ones tensor: 
tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]) 

Zeros tensor: 
tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]) 

Random (uniform) tensor: 
tensor([[[0.3461, 0.4716, 0.9937, 0.6279, 0.3561],
         [0.7074, 0.3792, 0.7300, 0.7096, 0.0383],
         [0.3449, 0.5702, 0.8236, 0.3064, 0.2357]],

        [[0.9269, 0.3137, 0.4431, 0.0266, 0.7653],
         [0.1353, 0.5216, 0.8716, 0.5607, 0.5371],
         [0.1115, 0.6260, 0.8500, 0.1038, 0.8973]]]) 

Random (Gaussian) tensor: 
tensor([[[-0.6795, -0.4159,  0.9827, -1.0309, -1.3561],
         [-0.3122, -0.5358, -0.3764,  0.8683,  1.3436],
         [-1.6786, -0.8016,  1.4672,  0.3639, -1.1457]],

        [[-1.3856, -0.1928, -0.5037, -1.3272, -0.912

### Moving back and forth between numpy and torch

In [ ]:
# Define numpy ndarray
x_numpy = np.array([[1.0, 0.0], [0.0, 1.0]])
print(x_numpy, '\n')

# Convert numpy ndarray to tensor
x_tensor = torch.from_numpy(x_numpy)
print(x_tensor)
print('Data type:', x_tensor.dtype, '\n')

# Convert back to numpy array
x_numpy2 = x_tensor.numpy()
print(x_numpy)

[[1. 0.]
 [0. 1.]] 

tensor([[1., 0.],
        [0., 1.]], dtype=torch.float64)
Data type: torch.float64 

[[1. 0.]
 [0. 1.]]


### Changing the data type of a tensor

In [ ]:
# Change data type to float32 
x_tensor = x_tensor.float()
print(f'{x_tensor}\n{x_tensor.dtype}\n')

# Change data type to int 
x_tensor_int = x_tensor.int()
print(f'{x_tensor_int}\n{x_tensor_int.dtype}\n')


# Change data type to int 
x_tensor_bool = x_tensor.bool()
print(f'{x_tensor_bool}\n{x_tensor_bool.dtype}\n')

tensor([[1., 0.],
        [0., 1.]])
torch.float32

tensor([[1, 0],
        [0, 1]], dtype=torch.int32)
torch.int32

tensor([[ True, False],
        [False,  True]])
torch.bool



### Changing the shape of a tensor

In [ ]:
x = torch.randn(size=(32, 2))
print(x.shape)
# reshape to (16, 4)
x = x.reshape((16, 4))
print(x.shape)
# add third dimension of size 1 (same as x.reshape((16, 4, 1)))
x = x.unsqueeze(-1)
print(x.shape)
# remove all dimensions of size 1
x = x.squeeze()
print(x.shape)
# flatten the tensor to a 1-dimensional vector (same as x.reshape((-1,)))
x = x.flatten()  
print(x.shape)

torch.Size([32, 2])
torch.Size([16, 4])
torch.Size([16, 4, 1])
torch.Size([16, 4])
torch.Size([64])


### Slicing tensors

In [ ]:
mat = torch.tensor([[0.0, 0.0, 0.0], [1.0, 1.0, 1.0], [2.0, 2.0, 2.0]])
print(mat)
# select first row
print(mat[0])
# select last column
print(mat[:, -1])
# select first two rows
print(mat[:2])
# select first and last column
print(mat[:, [0, -1]])

tensor([[0., 0., 0.],
        [1., 1., 1.],
        [2., 2., 2.]])
tensor([0., 0., 0.])
tensor([0., 1., 2.])
tensor([[0., 0., 0.],
        [1., 1., 1.]])
tensor([[0., 0.],
        [1., 1.],
        [2., 2.]])


### Moving tensors between the CPU and GPU

In [ ]:
x_tensor = torch.ones(3) # create 3x3 identity matrix
print(x_tensor.device)
x_tensor_gpu = x_tensor.cuda() # move tensor to GPU
print(x_tensor_gpu.device)

cpu
cuda:0


For computations, all involved tensors need to be located on the same device!

In [ ]:
x_tensor * (x_tensor_gpu + 1.0) # element wise product of vectors

RuntimeError: ignored

In [ ]:
x_result = x_tensor.cuda() * (x_tensor_gpu + 1.0)  # element wise product of vectors
print(x_result)

tensor([2., 2., 2.], device='cuda:0')


We can only convert **cpu** tensors into numpy ndarrays

In [ ]:
x_result.numpy()

TypeError: ignored

In [ ]:
x_result.cpu().numpy() # first move tensor back to cpu, then convert to numpy

array([2., 2., 2.], dtype=float32)

### Basic arithmetic operations

Scalar / element-wise operations

In [ ]:
a, b, c = torch.tensor(3.0), torch.tensor(2.0), torch.tensor(16.)
print(a+b)  # addition
print(a-b)  # subtraction
print(a*b)  # multiplication
print(a/b)  # division
print(a**b) # power
print(torch.sqrt(c)) # square root
print(torch.tensor([9.0, 16.])**0.5)  # square root as power
print(torch.exp(torch.zeros(2))) # exp

tensor(5.)
tensor(1.)
tensor(6.)
tensor(1.5000)
tensor(9.)
tensor(4.)
tensor([3., 4.])
tensor([1., 1.])


In [ ]:
mat1 = torch.tensor([[1.0, 2.0],[-2.0, 1.0]])
mat_eye = torch.eye(2) # identiy matrix
print(mat1)
print(mat_eye)

tensor([[ 1.,  2.],
        [-2.,  1.]])
tensor([[1., 0.],
        [0., 1.]])


In [ ]:
2 * mat1 - 1.0


tensor([[ 1.,  3.],
        [-5.,  1.]])

In [ ]:
mat1 - mat_eye

tensor([[ 0.,  2.],
        [-2.,  0.]])

In [ ]:
mat1 * mat_eye  # element-wise product

tensor([[1., 0.],
        [-0., 1.]])

Matrix multiplication and other matrix operations

In [ ]:
torch.matmul(mat1, mat_eye)

tensor([[ 1.,  2.],
        [-2.,  1.]])

In [ ]:
mat1 @ mat_eye  # @ is the short symbol for matmul 

tensor([[ 1.,  2.],
        [-2.,  1.]])

In [ ]:
mat1 @ torch.ones(2)  # matrix-vector product, (2, 2) @ (2,) -> (2,). 

tensor([ 3., -1.])

In [ ]:
mat1.T  # transpose

tensor([[ 1., -2.],
        [ 2.,  1.]])

In [ ]:
torch.linalg.cholesky(torch.eye(3) + torch.ones((3, 3))) # cholesky decomposition

tensor([[1.4142, 0.0000, 0.0000],
        [0.7071, 1.2247, 0.0000],
        [0.7071, 0.4082, 1.1547]])

### Reduce operations


In [ ]:
# reduce operations over entire tensor; (n, m) tensor -> scalar
x_mat = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
print('Original shape:', x_mat.shape)
print('Sum:', torch.sum(x_mat))
print('Mean:', torch.mean(x_mat))
print('Std:', torch.std(x_mat))
print('Product:', torch.prod(x_mat))

Original shape: torch.Size([2, 3])
Sum: tensor(21.)
Mean: tensor(3.5000)
Std: tensor(1.8708)
Product: tensor(720.)


In [ ]:
# reduce operations along a dimesion (last dimension being -1); (n, m) tensor -> (n,) tensor
x_mat = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
print('Sum:', torch.sum(x_mat, dim=-1))  # same as torch.sum(x_mat, dim=1)
print('Mean:', torch.mean(x_mat, dim=-1))
print('Std:', torch.std(x_mat, dim=-1))
print('Product:', torch.prod(x_mat, dim=-1))

Sum: tensor([ 6., 15.])
Mean: tensor([2., 5.])
Std: tensor([1., 1.])
Product: tensor([  6., 120.])


In [ ]:
y_mat = torch.rand((2, 3, 4))
print('y_mat:', y_mat)
print('Sum:', torch.sum(y_mat, dim=(0, -1)))

y_mat: tensor([[[2.0484e-01, 4.9108e-01, 1.0014e-05, 3.2200e-01],
         [2.4065e-01, 3.3344e-01, 4.5353e-01, 4.0415e-01],
         [2.0547e-01, 3.8172e-02, 2.2652e-01, 4.0503e-01]],

        [[5.9461e-01, 6.5301e-01, 8.4589e-01, 9.4166e-01],
         [9.7086e-02, 1.2127e-01, 7.7180e-01, 3.2549e-01],
         [7.9233e-01, 3.4888e-01, 1.9080e-01, 5.9989e-01]]])
Sum: tensor([4.0531, 2.7474, 2.8071])
